//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCAddress
    {
        public LCAddress()
        {
            this.LCEvents = new HashSet<LCEvent>();
        }
    
        public int AddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public int StateProvinceID { get; set; }
        public string PostalCode { get; set; }
        public System.Data.Spatial.DbGeography SpatialGeolocation { get; set; }
    
        public virtual LCStateProvince LCStateProvince { get; set; }
        public virtual ICollection<LCEvent> LCEvents { get; set; }
    }
}
