//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCCountry
    {
        public LCCountry()
        {
            this.LCStateProvinces = new HashSet<LCStateProvince>();
        }
    
        public string CountryRegionCode { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<LCStateProvince> LCStateProvinces { get; set; }
    }
}
