//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LCDB2Entities : DbContext
    {
        public LCDB2Entities()
            : base("name=LCDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LCAddress> LCAddresses { get; set; }
        public DbSet<LCCountry> LCCountries { get; set; }
        public DbSet<LCEvent> LCEvents { get; set; }
        public DbSet<LCEventCreation> LCEventCreations { get; set; }
        public DbSet<LCParticipation> LCParticipations { get; set; }
        public DbSet<LCStateProvince> LCStateProvinces { get; set; }
        public DbSet<LCUser> LCUsers { get; set; }
    }
}
