//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEvent
    {
        public LCEvent()
        {
            this.LCEventCreations = new HashSet<LCEventCreation>();
            this.LCParticipations = new HashSet<LCParticipation>();
        }
    
        public int EventId { get; set; }
        public string TimeSlots { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string EventGUID { get; set; }
    
        public virtual LCAddress LCAddress { get; set; }
        public virtual ICollection<LCEventCreation> LCEventCreations { get; set; }
        public virtual ICollection<LCParticipation> LCParticipations { get; set; }
    }
}
