//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEventCreation
    {
        public int UserId { get; set; }
        public int EventId { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual LCEvent LCEvent { get; set; }
        public virtual LCUser LCUser { get; set; }
    }
}
