//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCStateProvince
    {
        public LCStateProvince()
        {
            this.LCAddresses = new HashSet<LCAddress>();
        }
    
        public int StateProvinceID { get; set; }
        public string StateProvinceCode { get; set; }
        public string CountryRegionCode { get; set; }
        public string StateProvinceName { get; set; }
    
        public virtual ICollection<LCAddress> LCAddresses { get; set; }
        public virtual LCCountry LCCountry { get; set; }
    }
}
