//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCUser
    {
        public LCUser()
        {
            this.LCEventCreations = new HashSet<LCEventCreation>();
            this.LCParticipations = new HashSet<LCParticipation>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<LCEventCreation> LCEventCreations { get; set; }
        public virtual ICollection<LCParticipation> LCParticipations { get; set; }
    }
}
