//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiangchenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string Email { get; set; }
        public int SessionID { get; set; }
        public System.DateTime StartTime { get; set; }
        public string IP { get; set; }
        public string AccessToken { get; set; }
        public int Duration { get; set; }
    
        public virtual User User { get; set; }
    }
}
